apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiresense-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.1
    helm:
      values: |
        adminPassword: "admin"
        
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: InfluxDB
              type: influxdb
              access: proxy
              url: http://influxdb.default.svc.cluster.local:8086
              isDefault: true
              # Aqui está a mudança para V2 (Flux)
              jsonData:
                version: Flux
                organization: wiresense-org
                defaultBucket: wiresense
                tlsSkipVerify: true
              secureJsonData:
                token: "meu-token-admin-super-secreto"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true