import React, { createContext, useContext, useState, useEffect } from 'react';

// --- Translations Registry ---
export const TRANSLATIONS = {
    pt: {
        // Menu
        dashboard: "Visão Geral",
        devices: "Dispositivos",
        simulator: "Simulador",
        achievements: "Conquistas",
        reports: "Relatórios",
        history: "Histórico",
        settings: "Configurações",
        logout: "Sair",
        profile: "Meu Perfil",
        current_location: "Localização Atual",
        unknown_location: "Local Desconhecido",
        location_not_found: "Local não encontrado.",

        // Dashboard
        welcome: "Bem-vindo de volta",
        energy_status: "Status Energético",
        consumption: "Consumo",
        generation: "Geração",
        net_balance: "Saldo da Rede",

        active_devices: "Dispositivos Ativos",
        generated: "Total Gerado",
        simulations: "Simulações",
        streak: "Sequência",
        days: "Dias",
        performance_overview: "Desempenho",

        // Dashboard Status
        simulation_mode: "Modo Simulado",
        system_online: "Sistema Online",
        simulation_active_banner: "Simulação Ativa",
        devices_active: "Dispositivos Ativos",
        manage: "Gerenciar",
        stop_all: "Parar Tudo",
        test_env_desc: "Ambiente de testes ativo. Dados e custos são estimativas projetadas.",
        solar_monitoring_desc: "Monitoramento da sua usina solar em tempo real.",
        consumption_monitoring_desc: "Monitoramento do consumo elétrico da residência.",

        // Dashboard Cards
        power_now: "Potência Agora",
        current: "Corrente",
        energy_today: "Energia (Hoje)",
        energy_month: "Energia (Mês)",
        savings: "Economia",
        cost: "Custo",
        estimate_day: "Estimativa (Dia)",
        estimate_month: "Estimativa (Mês)",
        generation_today: "Geração (Hoje)",
        generation_month: "Geração (Mês)",
        consumption_today: "Consumo (Hoje)",
        consumption_month: "Consumo (Mês)",
        monthly_goal: "Meta de Geração Mensal",
        monthly_budget: "Orçamento Mensal Utilizado",

        // Devices Page
        manage_devices: "Gerenciar Dispositivos",
        total: "Total",
        manage_devices_desc: "Adicione e gerencie seus medidores de consumo e geração.",
        new_device: "Novo Dispositivo",
        active: "Ativo",
        configure: "Configurar",
        add_new_device: "Adicionar Novo Dispositivo",
        device_name: "Nome do Dispositivo",
        device_type: "Tipo de Dispositivo",
        device_name_placeholder: "Ex: Ar Condicionado Sala",
        delete_device_title: "Excluir Dispositivo?",
        delete_device_desc: "Esta ação é irreversível. O dispositivo e seu histórico serão removidos permanentemente.",
        create_device: "Criar Dispositivo",
        consumer: "Consumidor",
        generator: "Gerador",

        // Simulator Page
        load_simulator: "Simulador de Carga",
        simulator_desc: "Simule o consumo de dispositivos reais ou fictícios para testar o sistema.",
        devices_count: "dispositivos",
        devices_in_use: "Dispositivos em uso",
        stop_full_simulation: "Parar Simulação Completa",
        manual_simulation: "Simulação Manual",
        power_watts: "Potência (Watts)",
        fluctuation: "Flutuação (%)",
        simulate: "Simular",
        my_devices: "Meus Dispositivos",
        basic_info: "Informações Básicas",
        fluctuation_sim: "Flutuação (Simulação)",
        icon: "Ícone",
        card_color: "Cor do Card",
        save_device: "Salvar Dispositivo",
        no_saved_devices: "Nenhum dispositivo salvo. Adicione o primeiro acima!",
        ready_examples: "Exemplos Prontos",
        remove_saved_device: "Remover Dispositivo Salvo?",
        remove_saved_device_desc: "Isso removerá este dispositivo da sua lista de salvos permanentemente.",

        // Simulator Presets & Colors
        electric_shower: "Chuveiro Elétrico",
        air_conditioner: "Ar Condicionado",
        electric_car: "Carro Elétrico",
        hair_dryer: "Secador de Cabelo",
        microwave: "Microondas",
        gaming_pc: "PC Gamer",

        color_blue: "Azul",
        color_cyan: "Ciano",
        color_emerald: "Esmeralda",
        color_green: "Verde",
        color_yellow: "Amarelo",
        color_orange: "Laranja",
        color_red: "Vermelho",
        color_pink: "Rosa",
        color_purple: "Roxo",
        remove: "Remover",

        // Reports Page
        consolidated_reports: "Relatórios Consolidados",
        reports_desc: "Visão geral do impacto de todos os seus dispositivos.",
        multi_device_report: "Relatório Multi-Dispositivo",
        estimated_values: "Valores estimados baseados em sensores",
        issue_date: "Data de Emissão",
        calculating: "Calculando dados...",
        consumption_cost: "Custo Consumo",
        produced_value: "Valor Produzido",
        net_estimated_cost: "Custo Líquido Estimado",
        device_breakdown: "Detalhamento por Dispositivo",
        device: "Dispositivo",
        type: "Tipo",
        consumption_generation_month: "Consumo/Geração (Mês)",
        base_tariff: "Tarifa Base",
        impact: "Impacto",
        estimation_warning: "Aviso de Estimativa",
        estimation_warning_text: "Os valores apresentados são calculados com base em sensores de corrente e configurações do usuário. Não representam uma fatura oficial da concessionária.",
        quotes: "Cotações",
        print_pdf: "Imprimir / Salvar PDF",
        export_csv: "Exportar CSV",

        // History Page
        history_of: "Histórico de",
        detailed_analysis: "Análise detalhada ao longo do tempo.",
        daily: "Diário",
        monthly: "Mensal",
        days_7: "7 Dias",
        days_30: "30 Dias",
        months_6: "6 Meses",
        months_12: "12 Meses",
        data_breakdown: "Detalhamento dos Dados",
        date_period: "Data / Período",
        peak_current: "Pico de Corrente (A)",
        estimated_cost: "Custo Estimado",
        highlight_date: "Destacar Data",
        selected_date: "Data Selecionada",
        estimated_earnings: "Ganho Estimado",
        clear: "Limpar",

        // Settings Page
        customize_experience: "Personalize sua experiência no Wiresense.",
        electricity: "Eletricidade",
        grid_voltage: "Tensão da Rede (Voltagem)",
        voltage_desc: "Selecione a voltagem padrão da sua residência para cálculos corretos de potencia.",
        costs_currency: "Custos e Moeda",
        tariff_kwh: "Tarifa por kWh",
        display_currency: "Moeda de Exibição",
        monthly_budget_goal: "Meta de Orçamento Mensal",
        tariff_model: "Modelo Tarifário",
        conventional_desc: "Valor único para kWh em qualquer horário.",
        white_tariff: "Tarifa Branca",
        white_tariff_desc: "Preços variam: Ponta (Caro), Intermediário e Fora de Ponta (Barato).",
        peak_start_time: "Horário de Início da Ponta (Vermelha)",
        check_bill_desc: "Consulte sua conta de luz. Geralmente começa às 18h ou 19h.",
        peak_time_label: "Horário de Ponta",
        intermediate_time_label: "Horário Intermediário",
        off_peak_time_label: "Fora de Ponta",
        remaining_hours_weekends: "Demais horários e fins de semana",
        current_config: "Configuração Atual",

        settings_desc: "Personalize suas preferências",
        network_voltage: "Tensão da Rede",
        phase_type: "Tipo de Fase",
        informative_only: "Apenas informativo",
        zero_to_disable: "0 para desativar",
        peak_start_hour: "Horário de Início da Ponta",
        peak_start_hour_desc: "Horário que inicia a cobrança mais cara.",
        white_tariff_cost_desc: "Custo base (Fora de Ponta)",
        conventional_tariff_cost_desc: "Custo único do kWh",
        conventional: "Convencional",
        base_cost_kwh: "Custo Base kWh",
        settings_device_name_placeholder: "Nome (Ex: Geladeira)",

        appearance_themes: "Aparência e Temas",
        customize_theme_desc: "Escolha o visual do seu dashboard",
        high_priority_alerts_desc: "Alertas críticos de sistema ou clima",
        alerts_notifications: "Alertas e Notificações",
        high_priority_alerts: "Alertas de Alta Prioridade",
        high_priority_desc: "Notificar sobre consumo excessivo (>6kW) ou tempestades.",
        weekly_report: "Relatório Semanal",
        weekly_report_desc: "Receba um resumo de custos toda segunda-feira.",
        educational_tips: "Dicas Educativas",
        educational_tips_desc: "Exibir dicas de economia no Dashboard.",
        restart_tutorial: "Reiniciar Tutorial",

        single_phase: "Monofásico",
        two_phase: "Bifásico",
        three_phase: "Trifásico",

        // Profile Page
        personal_info: "Informações Pessoais",
        profile_desc: "Gerencie suas informações e segurança.",
        your_name: "Seu Nome",
        display_name_desc: "Como você será chamado no sistema.",
        email: "E-mail",
        email_change_notice: "Para alterar seu e-mail, entre em contato com o suporte.",
        display_name: "Nome de Exibição",
        name_placeholder: "Seu nome",
        name_visibility_desc: "Este nome será visível no dashboard e relatórios.",
        email_managed: "Email (Gerenciado pelo Google)",
        save_changes: "Salvar Alterações",
        profile_updated: "Perfil atualizado com sucesso!",
        profile_error: "Erro ao atualizar perfil.",
        secure_account: "Conta Segura",
        secure_account_desc: "Você está autenticado via Google Secure Login.",

        // Achievements
        tier_bronze: "Bronze",
        tier_silver: "Prata",
        tier_gold: "Ouro",
        tier_legendary: "Lendário",
        achievements_desc: "Acompanhe seu progresso, eficiência e domínio do sistema. Desbloqueie medalhas e equipe sua favorita no perfil.",
        level: "Nível",
        equipped: "Equipado",
        progress: "Progresso",

        ach_hello_world_name: "Primeiro Passo",
        ach_hello_world_desc: "Acesse o Dashboard pela primeira vez.",
        ach_first_spark_name: "Primeira Faísca",
        ach_first_spark_desc: "Adicione seu primeiro dispositivo ao sistema.",
        ach_observer_name: "Observador",
        ach_observer_desc: "Acesse a página do Simulador.",
        ach_theme_park_name: "Estilista",
        ach_theme_park_desc: "Mude o tema do dashboard 3 vezes.",
        ach_configurator_name: "Engenheiro",
        ach_configurator_desc: "Ajuste configurações de tarifa ou tensão.",
        ach_simulation_fan_name: "Cientista de Dados",
        ach_simulation_fan_desc: "Execute 10 simulações de carga.",
        ach_fully_loaded_name: "Casa Inteligente",
        ach_fully_loaded_desc: "Tenha 5 ou mais dispositivos cadastrados.",
        ach_night_owl_name: "Vigilante Noturno",
        ach_night_owl_desc: "Acesse o sistema entre 1h e 5h da manhã.",
        ach_multipower_name: "Multitarefa",
        ach_multipower_desc: "Execute 3 simulações simultâneas.",
        ach_efficiency_expert_name: "Ecológico",
        ach_efficiency_expert_desc: "Registre um dispositivo Solar.",
        ach_solar_titan_name: "Titã Solar",
        ach_solar_titan_desc: "Gere um total de 500 kWh de energia.",
        ach_grid_guardian_name: "Guardião da Rede",
        ach_grid_guardian_desc: "Execute 50 Simulações.",
        ach_energy_tycoon_name: "Magnata",
        ach_energy_tycoon_desc: "Economia virtual acumulada de R$ 1.000,00.",
        ach_overload_name: "Sobrecarga",
        ach_overload_desc: "Simule uma corrente acima de 50A.",
        ach_collector_name: "Colecionador",
        ach_collector_desc: "Desbloqueie 10 conquistas.",
        ach_energy_god_name: "Deus da Energia",
        ach_energy_god_desc: "Gere 1 MegaWatt-hora (1000 kWh).",
        ach_timeless_name: "Atemporal",
        ach_timeless_desc: "Acesse o app por 7 dias distintos.",
        unlocked_title: "Conquista Desbloqueada! 🏆",
        unlocked_message: "Você desbloqueou: {name}",

        // Charts
        power: "Potência",
        realtime_power: "Potência em Tempo Real",
        realtime_current: "Corrente em Tempo Real",

        // Smart Tips
        tip_edu_led: 'Dica: Lâmpadas LED economizam até 80% de energia.',
        tip_edu_standby: 'Sabia? Standby pode custar até 12% da conta.',
        tip_edu_shower: 'Banhos: -5 min pode economizar R$ 30,00/mês.',
        tip_edu_fridge: 'Geladeira: Evite abrir a porta desnecessariamente.',
        tip_edu_iron: 'Ferro: Passe o máximo de roupas de uma vez.',
        tip_edu_ac_filter: 'Manutenção: Limpe filtros de ar condicionado.',
        tip_edu_natural_light: 'Dia claro? Use a luz natural!',
        tip_edu_peak: 'Evite máquinas de lavar no horário de ponta.',
        tip_edu_solar_clean: 'Painéis Solares: Verifique limpeza.',
        tip_edu_tv_sleep: 'Dormiu na TV? Use o Sleep.',
        tip_edu_charger: 'Desplugue carregadores sem uso.',
        tip_edu_seal: 'Ar Condicionado: Feche portas e janelas.',
        tip_peak_active: 'Horário de Ponta! Tarifa cara.',
        tip_inter_active: 'Tarifa Intermediária. Preço subindo.',
        tip_budget_warn: 'Cuidado: 90% do orçamento atingido',
        tip_rain_solar: 'Chuva reduz geração solar.',
        tip_storm_alert: 'Tempestade! Proteja equipamentos.',
        tip_good_solar: 'Sol bombando! ☀️ Aproveite para consumir.',
        tip_high_temp: 'lá fora! Ar condicionado trabalhando muito.',
        tip_low_temp: 'Noite fria! Aquecedores gastam muito.',
        tip_vampire_power: 'Alto consumo na madrugada. Standby?',
        tip_heavy_load: 'Consumo altíssimo (>6kW)! Cuidado.',
        tip_weekend_laundry: 'Fim de semana: Tarifa barata.',
        tip_friday_night: 'Sextou! 🍿 Bom descanso.',
        tip_solar_momentum: 'Momento Mágico! 🌟 Excedente alto.',
        tip_solar_gold: 'Lucro Máximo! 💰 Fugindo da ponta.',
        tip_quiet_night: 'Madrugada tranquila. Tudo certo.',
        tip_ac_efficiency: 'Calor fora, consumo controlado. Boa!',
        tip_voltage_instability: 'Tensão instável. Risco!',
        tip_default_safe: 'Sistema operando normalmente.',

        // Smart Weather Card
        city_placeholder: "Cidade...",
        analyzing_system: "Analisando sistema...",
        clear_sky: "Céu Limpo",
        partly_cloudy: "Parcialmente Nublado",
        rain: "Chuva",
        storm: "Tempestade",
        normal: "Normal",
        high_priority: "Alta Prioridade",
        warning: "Atenção",
        opportunity: "Oportunidade",
        tip: "Dica",

        // Tariff Card
        off_peak: "Fora de Ponta",
        peak_expensive: "Ponta (Caro)",
        intermediate: "Intermediário",
        peak_warning: "Tarifa mais cara! Evite usar chuveiro, ferro e máquinas agora.",
        intermediate_warning: "Tarifa subindo. Atenção ao consumo.",
        off_peak_recommendation: "Melhor horário para usar eletrodomésticos pesados.",

        // Common
        notifications: "Notificações",
        new: "novas",
        mark_all_read: "Marcar todas como lidas",
        clear_all: "Limpar tudo",
        no_notifications: "Nada por aqui...",
        monitoring: "Monitorando",
        select_device: "Selecione o Dispositivo",
        select_network_voltage: "Selecione a Voltagem da Rede",
        custom: "Customizada",
        enter_voltage: "Digite a voltagem",
        no_data_export: "Sem dados para exportar.",

        peak_load_title: "Picos de Carga",
        peak_load_desc: "Corrente máxima registrada por dia",
        amperes: "Amperes",
        cost_evolution: "Evolução de Custos",
        based_on_tariff: "Baseado na tarifa configurada",
        no_history_data: "Sem dados históricos para este dispositivo.",

        // Notifications
        notif_system_started: "Sistema Iniciado",
        notif_system_started_desc: "Monitoramento em tempo real ativo. Bem-vindo ao WireSense.",
        notif_peak_load: "Pico de Consumo",
        notif_peak_load_desc: "Detectado pico de 4.2kW no Ar Condicionado.",
        notif_tariff_update: "Tarifa Atualizada",
        notif_tariff_update_desc: "A tarifa mudou para Intermediária (R$ 0,89/kWh).",
        notif_device_connected: "Dispositivo Conectado",
        notif_device_connected_desc: "Novo dispositivo 'Smart TV' detectado na rede.",
        notif_goal_reached: "Meta Atingida",
        notif_goal_reached_desc: "Você atingiu 80% do orçamento mensal estipulado.",
        notif_savings_generated: "Economia Gerada",
        notif_savings_generated_desc: "Seus painéis economizaram R$ 12,50 hoje.",
        notif_voltage_unstable: "Tensão Instável",
        notif_voltage_unstable_desc: "Variação de tensão detectada (118V -> 109V).",
        notif_report_ready: "Relatório Disponível",
        notif_report_ready_desc: "O relatório semanal de eficiência está pronto.",
        loading: "Carregando...",
        error: "Ocorreu um erro",
        save: "Salvar",
        cancel: "Cancelar",
        delete: "Excluir",
        edit: "Editar",
        confirm: "Confirmar",
        configure_system: "Configurar sistema",

        // Settings
        appearance: "Aparência e Temas",
        language: "Idioma",
    },
    en: {
        dashboard: "Dashboard",
        devices: "Devices",
        simulator: "Simulator",
        achievements: "Achievements",
        reports: "Reports",
        history: "History",
        settings: "Settings",
        logout: "Logout",
        profile: "My Profile",
        current_location: "Current Location",
        unknown_location: "Unknown Location",
        location_not_found: "Location not found.",

        welcome: "Welcome back",
        energy_status: "Energy Status",
        consumption: "Consumption",
        generation: "Generation",
        net_balance: "Net Balance",
        active_devices: "Active Devices",
        generated: "Total Generated",
        simulations: "Simulations",
        streak: "Streak",
        days: "Days",
        performance_overview: "Performance Overview",

        simulation_mode: "Simulation Mode",
        system_online: "System Online",
        simulation_active_banner: "Simulation Active",
        devices_active: "Active Devices",
        manage: "Manage",
        stop_all: "Stop All",
        test_env_desc: "Active test environment. Data and costs are projected estimates.",
        solar_monitoring_desc: "Real-time monitoring of your solar plant.",
        consumption_monitoring_desc: "Monitoring of residential electricity consumption.",

        power_now: "Power Now",
        current: "Current",
        energy_today: "Energy (Today)",
        energy_month: "Energy (Month)",
        savings: "Savings",
        cost: "Cost",
        estimate_day: "Estimate (Day)",
        estimate_month: "Estimate (Month)",
        generation_today: "Generation (Today)",
        generation_month: "Generation (Month)",
        consumption_today: "Consumption (Today)",
        consumption_month: "Consumption (Month)",
        monthly_goal: "Monthly Generation Goal",
        monthly_budget: "Monthly Budget Used",

        // Devices Page
        manage_devices: "Manage Devices",
        total: "Total",
        manage_devices_desc: "Add and manage your consumption and generation meters.",
        new_device: "New Device",
        active: "Active",
        configure: "Configure",
        add_new_device: "Add New Device",
        device_name: "Device Name",
        device_type: "Device Type",
        device_name_placeholder: "Ex: Living Room AC",
        delete_device_title: "Delete Device?",
        delete_device_desc: "This action is irreversible. The device and its history will be permanently removed.",
        create_device: "Create Device",
        consumer: "Consumer",
        generator: "Generator",

        // Simulator Page
        load_simulator: "Load Simulator",
        simulator_desc: "Simulate real or fictional devices to test the system.",
        devices_count: "devices",
        devices_in_use: "Devices in use",
        stop_full_simulation: "Stop Full Simulation",
        manual_simulation: "Manual Simulation",
        power_watts: "Power (Watts)",
        fluctuation: "Fluctuation (%)",
        simulate: "Simulate",
        my_devices: "My Devices",
        basic_info: "Basic Info",
        fluctuation_sim: "Fluctuation (Simulation)",
        icon: "Icon",
        card_color: "Card Color",
        save_device: "Save Device",
        no_saved_devices: "No saved devices. Add your first one above!",
        ready_examples: "Ready Examples",
        remove_saved_device: "Remove Saved Device?",
        remove_saved_device_desc: "This will permanently remove this device from your saved list.",

        // Simulator Presets & Colors
        electric_shower: "Electric Shower",
        air_conditioner: "Air Conditioner",
        electric_car: "Electric Car",
        hair_dryer: "Hair Dryer",
        microwave: "Microwave",
        gaming_pc: "Gaming PC",

        color_blue: "Blue",
        color_cyan: "Cyan",
        color_emerald: "Emerald",
        color_green: "Green",
        color_yellow: "Yellow",
        color_orange: "Orange",
        color_red: "Red",
        color_pink: "Pink",
        color_purple: "Purple",
        remove: "Remove",

        // Reports Page
        consolidated_reports: "Consolidated Reports",
        reports_desc: "Overview of the impact of all your devices.",
        multi_device_report: "Multi-Device Report",
        estimated_values: "Estimated values based on sensors",
        issue_date: "Issue Date",
        calculating: "Calculating data...",
        consumption_cost: "Consumption Cost",
        produced_value: "Produced Value",
        net_estimated_cost: "Net Estimated Cost",
        device_breakdown: "Device Breakdown",
        device: "Device",
        type: "Type",
        consumption_generation_month: "Consumption/Generation (Month)",
        base_tariff: "Base Tariff",
        impact: "Impact",
        estimation_warning: "Estimation Warning",
        estimation_warning_text: "Values shown are calculated based on current sensors and user settings. They do not represent an official utility bill.",
        quotes: "Quotes",
        print_pdf: "Print / Save PDF",
        export_csv: "Export CSV",

        // History Page
        history_of: "History of",
        detailed_analysis: "Detailed analysis over time.",
        daily: "Daily",
        monthly: "Monthly",
        days_7: "7 Days",
        days_30: "30 Days",
        months_6: "6 Months",
        months_12: "12 Months",
        data_breakdown: "Data Breakdown",
        date_period: "Date / Period",
        peak_current: "Peak Current (A)",
        estimated_cost: "Estimated Cost",
        highlight_date: "Highlight Date",
        selected_date: "Selected Date",
        estimated_earnings: "Estimated Earnings",
        clear: "Clear",

        // Settings Page
        customize_experience: "Customize your Wiresense experience.",
        electricity: "Electricity",
        grid_voltage: "Grid Voltage",
        voltage_desc: "Select your home's standard voltage for correct power calculations.",
        costs_currency: "Costs & Currency",
        tariff_kwh: "Tariff per kWh",
        display_currency: "Display Currency",
        monthly_budget_goal: "Monthly Budget Goal",
        tariff_model: "Tariff Model",
        conventional_desc: "Single rate for kWh at any time.",
        white_tariff: "White Tariff",
        white_tariff_desc: "Prices vary: Peak (Expensive), Intermediate, and Off-Peak (Cheap).",
        peak_start_time: "Peak Start Time (Red)",
        check_bill_desc: "Check your electricity bill. Usually starts at 18h or 19h.",
        peak_time_label: "Peak Time",
        intermediate_time_label: "Intermediate Time",
        off_peak_time_label: "Off-Peak Time",
        remaining_hours_weekends: "Remaining hours and weekends",
        current_config: "Current Config",

        settings_desc: "Customize your preferences",
        network_voltage: "Network Voltage",
        phase_type: "Phase Type",
        informative_only: "Informative only",
        zero_to_disable: "0 to disable",
        peak_start_hour: "Peak Start Hour",
        peak_start_hour_desc: "Time when the most expensive rate starts.",
        white_tariff_cost_desc: "Base cost (Off-Peak)",
        conventional_tariff_cost_desc: "Single kWh cost",
        conventional: "Conventional",
        base_cost_kwh: "Base Cost kWh",
        settings_device_name_placeholder: "Name (Ex: Fridge)",

        appearance_themes: "Appearance & Themes",
        customize_theme_desc: "Choose your dashboard look",
        high_priority_alerts_desc: "Critical system or weather alerts",
        alerts_notifications: "Alerts & Notifications",
        high_priority_alerts: "High Priority Alerts",
        high_priority_desc: "Notify about excessive consumption (>6kW) or storms.",
        weekly_report: "Weekly Report",
        weekly_report_desc: "Receive a cost summary every Monday.",
        educational_tips: "Educational Tips",
        educational_tips_desc: "Show saving tips on Dashboard.",
        restart_tutorial: "Restart Tutorial",

        single_phase: "Single Phase",
        two_phase: "Two Phase",
        three_phase: "Three Phase",

        // Profile Page
        personal_info: "Personal Information",
        profile_desc: "Manage your information and security.",
        your_name: "Your Name",
        display_name_desc: "How you will be addressed in the system.",
        email: "Email",
        email_change_notice: "To change your email, please contact support.",
        display_name: "Display Name",
        name_placeholder: "Your name",
        name_visibility_desc: "This name will be visible on dashboard and reports.",
        email_managed: "Email (Managed by Google)",
        save_changes: "Save Changes",
        profile_updated: "Profile updated successfully!",
        profile_error: "Error updating profile.",
        secure_account: "Secure Account",
        secure_account_desc: "You are authenticated via Google Secure Login.",

        // Achievements
        tier_bronze: "Bronze",
        tier_silver: "Silver",
        tier_gold: "Gold",
        tier_legendary: "Legendary",
        achievements_desc: "Track your progress, efficiency, and system mastery. Unlock badges and equip your favorite one.",
        level: "Level",
        equipped: "Equipped",
        progress: "Progress",

        ach_hello_world_name: "First Step",
        ach_hello_world_desc: "Access the Dashboard for the first time.",
        ach_first_spark_name: "First Spark",
        ach_first_spark_desc: "Add your first device to the system.",
        ach_observer_name: "Observer",
        ach_observer_desc: "Visit the Simulator page.",
        ach_theme_park_name: "Stylist",
        ach_theme_park_desc: "Change the dashboard theme 3 times.",
        ach_configurator_name: "Engineer",
        ach_configurator_desc: "Adjust tariff or voltage settings.",
        ach_simulation_fan_name: "Data Scientist",
        ach_simulation_fan_desc: "Run 10 load simulations.",
        ach_fully_loaded_name: "Smart Home",
        ach_fully_loaded_desc: "Have 5 or more devices registered.",
        ach_night_owl_name: "Night Owl",
        ach_night_owl_desc: "Access the system between 1 AM and 5 AM.",
        ach_multipower_name: "Multitasker",
        ach_multipower_desc: "Run 3 simultaneous simulations.",
        ach_efficiency_expert_name: "Eco-Friendly",
        ach_efficiency_expert_desc: "Register a Solar device.",
        ach_solar_titan_name: "Solar Titan",
        ach_solar_titan_desc: "Generate a total of 500 kWh of energy.",
        ach_grid_guardian_name: "Grid Guardian",
        ach_grid_guardian_desc: "Run 50 Simulations.",
        ach_energy_tycoon_name: "Tycoon",
        ach_energy_tycoon_desc: "Accumulated virtual savings of $ 1,000.00.",
        ach_overload_name: "Overload",
        ach_overload_desc: "Simulate a current over 50A.",
        ach_collector_name: "Collector",
        ach_collector_desc: "Unlock 10 achievements.",
        ach_energy_god_name: "Energy God",
        ach_energy_god_desc: "Generate 1 MegaWatt-hour (1000 kWh).",
        ach_timeless_name: "Timeless",
        ach_timeless_desc: "Access the app on 7 different days.",
        unlocked_title: "Achievement Unlocked! 🏆",
        unlocked_message: "You unlocked: {name}",

        // Charts
        power: "Power",
        realtime_power: "Realtime Power",
        realtime_current: "Realtime Current",

        // Smart Tips
        tip_edu_led: 'Tip: LED bulbs save up to 80% energy.',
        tip_edu_standby: 'Did you know? Standby can cost 12% of bill.',
        tip_edu_shower: 'Showers: -5 min saves money.',
        tip_edu_fridge: 'Fridge: Avoid opening door often.',
        tip_edu_iron: 'Iron: Iron clothes in batches.',
        tip_edu_ac_filter: 'Maintenance: Clean AC filters.',
        tip_edu_natural_light: 'Sunny day? Use natural light!',
        tip_edu_peak: 'Avoid heavy appliances during peak hours.',
        tip_edu_solar_clean: 'Solar Panels: Check cleanliness.',
        tip_edu_tv_sleep: 'TV Sleep timer saves energy.',
        tip_edu_charger: 'Unplug unused chargers.',
        tip_edu_seal: 'AC: Close doors and windows.',
        tip_peak_active: 'Peak Hour! Rates are high now.',
        tip_inter_active: 'Intermediate Rate. Price rising.',
        tip_budget_warn: 'Warning: 90% budget reached',
        tip_rain_solar: 'Rain reducing solar output.',
        tip_storm_alert: 'Storm! Protect equipment.',
        tip_good_solar: 'Sunny! ☀️ Good time to consume.',
        tip_high_temp: 'outside! AC working hard.',
        tip_low_temp: 'Cold night! Heaters use lots of power.',
        tip_vampire_power: 'High night usage. Check standby.',
        tip_heavy_load: 'Very High Load (>6kW)! Careful.',
        tip_weekend_laundry: 'Weekend: Cheap rates.',
        tip_friday_night: 'Friday! 🍿 Have a good rest.',
        tip_solar_momentum: 'Magic Moment! 🌟 High surplus.',
        tip_solar_gold: 'Max Profit! 💰 Avoiding peak rates.',
        tip_quiet_night: 'Quiet night. All good.',
        tip_ac_efficiency: 'Hot outside, managed usage. Nice!',
        tip_voltage_instability: 'Unstable voltage. Risk!',
        tip_default_safe: 'System operating normally.',

        city_placeholder: "City...",
        analyzing_system: "Analyzing system...",
        clear_sky: "Clear Sky",
        partly_cloudy: "Partly Cloudy",
        rain: "Rain",
        storm: "Storm",
        normal: "Normal",
        high_priority: "High Priority",
        warning: "Warning",
        opportunity: "Opportunity",
        tip: "Tip",

        off_peak: "Off-Peak",
        peak_expensive: "Peak (Expensive)",
        intermediate: "Intermediate",
        peak_warning: "Most expensive tariff! Avoid high-power devices now.",
        intermediate_warning: "Tariff rising. Watch your consumption.",
        off_peak_recommendation: "Best time to use heavy appliances.",

        // Common
        notifications: "Notifications",
        new: "new",
        mark_all_read: "Mark all as read",
        clear_all: "Clear all",
        no_notifications: "Nothing here...",
        monitoring: "Monitoring",
        select_device: "Select Device",
        select_network_voltage: "Select Network Voltage",
        custom: "Custom",
        enter_voltage: "Enter voltage",
        no_data_export: "No data to export.",
        export_csv: "Export CSV",
        peak_load_title: "Peak Load",
        peak_load_desc: "Max current recorded per day",
        amperes: "Amperes",
        cost_evolution: "Cost Evolution",
        based_on_tariff: "Based on configured tariff",
        no_history_data: "No history data available for this device.",

        // Notifications
        notif_system_started: "System Started",
        notif_system_started_desc: "Real-time monitoring active. Welcome to WireSense.",
        notif_peak_load: "Peak Load",
        notif_peak_load_desc: "Peak of 4.2kW detected on Air Conditioner.",
        notif_tariff_update: "Tariff Updated",
        notif_tariff_update_desc: "Tariff changed to Intermediate ($ 0.89/kWh).",
        notif_device_connected: "Device Connected",
        notif_device_connected_desc: "New device 'Smart TV' detected on network.",
        notif_goal_reached: "Goal Reached",
        notif_goal_reached_desc: "You reached 80% of your monthly budget.",
        notif_savings_generated: "Savings Generated",
        notif_savings_generated_desc: "Your panels saved $ 12.50 today.",
        notif_voltage_unstable: "Unstable Voltage",
        notif_voltage_unstable_desc: "Voltage variation detected (118V -> 109V).",
        notif_report_ready: "Report Available",
        notif_report_ready_desc: "Weekly efficiency report is ready.",
        loading: "Loading...",
        error: "An error occurred",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        confirm: "Confirm",
        configure_system: "Configure System",

        appearance: "Appearance & Themes",
        language: "Language",
    },
    es: {
        dashboard: "Tablero",
        devices: "Dispositivos",
        simulator: "Simulador",
        achievements: "Logros",
        reports: "Reportes",
        history: "Historial",
        settings: "Ajustes",
        logout: "Cerrar Sesión",
        profile: "Mi Perfil",
        current_location: "Ubicación Actual",
        unknown_location: "Ubicación Desconocida",
        location_not_found: "Ubicación no encontrada.",

        welcome: "Bienvenido de nuevo",
        energy_status: "Estado Energético",
        consumption: "Consumo",
        generation: "Generación",
        net_balance: "Balance de Red",
        active_devices: "Dispositivos Activos",
        generated: "Total Generado",
        simulations: "Simulaciones",
        streak: "Racha",
        days: "Días",
        performance_overview: "Rendimiento",

        simulation_mode: "Modo de Simulación",
        system_online: "Sistema en Línea",
        simulation_active_banner: "Simulación Activa",
        devices_active: "Dispositivos Activos",
        manage: "Gestionar",
        stop_all: "Detener Todo",
        test_env_desc: "Entorno de prueba activo. Datos y costos son estimaciones proyectadas.",
        solar_monitoring_desc: "Monitoreo de su planta solar en tiempo real.",
        consumption_monitoring_desc: "Monitoreo del consumo eléctrico residencial.",

        power_now: "Potencia Ahora",
        current: "Corriente",
        energy_today: "Energía (Hoy)",
        energy_month: "Energía (Mes)",
        savings: "Ahorro",
        cost: "Costo",
        estimate_day: "Estimación (Día)",
        estimate_month: "Estimación (Mes)",
        generation_today: "Generación (Hoy)",
        generation_month: "Generación (Mes)",
        consumption_today: "Consumo (Hoy)",
        consumption_month: "Consumo (Mes)",
        monthly_goal: "Meta de Generación Mensual",
        monthly_budget: "Presupuesto Mensual Utilizado",

        // Devices Page
        manage_devices: "Gestionar Dispositivos",
        total: "Total",
        manage_devices_desc: "Agregue y gestione sus medidores de consumo y generación.",
        new_device: "Nuevo Dispositivo",
        active: "Activo",
        configure: "Configurar",
        add_new_device: "Agregar Nuevo Dispositivo",
        device_name: "Nombre del Dispositivo",
        device_type: "Tipo de Dispositivo",
        device_name_placeholder: "Ej: Aire Acondicionado Sala",
        delete_device_title: "¿Eliminar Dispositivo?",
        delete_device_desc: "Esta acción es irreversible. El dispositivo y su historial serán eliminados permanentemente.",
        create_device: "Crear Dispositivo",
        consumer: "Consumidor",
        generator: "Generador",

        // Simulator Page
        load_simulator: "Simulador de Carga",
        simulator_desc: "Simule el consumo de dispositivos reales o ficticios para probar el sistema.",
        devices_count: "dispositivos",
        devices_in_use: "Dispositivos en uso",
        stop_full_simulation: "Detener Simulación Completa",
        manual_simulation: "Simulación Manual",
        power_watts: "Potencia (Watts)",
        fluctuation: "Fluctuación (%)",
        simulate: "Simular",
        my_devices: "Mis Dispositivos",
        basic_info: "Información Básica",
        fluctuation_sim: "Flutuación (Simulación)",
        icon: "Ícono",
        card_color: "Color de Tarjeta",
        save_device: "Guardar Dispositivo",
        no_saved_devices: "Ningún dispositivo guardado. ¡Agregue el primero arriba!",
        ready_examples: "Ejemplos Listos",
        remove_saved_device: "¿Eliminar Dispositivo Guardado?",
        remove_saved_device_desc: "Este dispositivo será eliminado de sus atajos del simulador.",
        remove: "Eliminar",

        // Simulator Presets & Colors
        electric_shower: "Ducha Eléctrica",
        air_conditioner: "Aire Acondicionado",
        electric_car: "Coche Eléctrico",
        hair_dryer: "Secador de Pelo",
        microwave: "Microondas",
        gaming_pc: "PC Gamer",

        color_blue: "Azul",
        color_cyan: "Cian",
        color_emerald: "Esmeralda",
        color_green: "Verde",
        color_yellow: "Amarillo",
        color_orange: "Naranja",
        color_red: "Rojo",
        color_pink: "Rosa",
        color_purple: "Morado",

        // Reports Page
        consolidated_reports: "Reportes Consolidados",
        reports_desc: "Visión general del impacto de todos sus dispositivos.",
        multi_device_report: "Reporte Multi-Dispositivo",
        estimated_values: "Valores estimados basados en sensores",
        issue_date: "Fecha de Emisión",
        calculating: "Calculando datos...",
        consumption_cost: "Costo de Consumo",
        produced_value: "Valor Producido",
        net_estimated_cost: "Costo Neto Estimado",
        device_breakdown: "Desglose por Dispositivo",
        device: "Dispositivo",
        type: "Tipo",
        consumption_generation_month: "Consumo/Generación (Mes)",
        base_tariff: "Tarifa Base",
        impact: "Impacto",
        estimation_warning: "Aviso de Estimación",
        estimation_warning_text: "Los valores mostrados se calculan en base a sensores actuales y configuraciones del usuario. No representan una factura oficial.",
        quotes: "Cotizaciones",
        print_pdf: "Imprimir / Guardar PDF",
        export_csv: "Exportar CSV",

        // History Page
        history_of: "Historial de",
        detailed_analysis: "Análisis detallado a lo largo del tiempo.",
        daily: "Diario",
        monthly: "Mensual",
        days_7: "7 Días",
        days_30: "30 Días",
        months_6: "6 Meses",
        months_12: "12 Meses",
        data_breakdown: "Desglose de Datos",
        date_period: "Fecha / Período",
        peak_current: "Pico de Corriente (A)",
        estimated_cost: "Costo Estimado",
        highlight_date: "Destacar Fecha",
        selected_date: "Fecha Selecionada",
        estimated_earnings: "Ganancia Estimada",
        clear: "Limpiar",

        // Settings Page
        customize_experience: "Personalice su experiencia en Wiresense.",
        electricity: "Electricidad",
        grid_voltage: "Voltaje de Red",
        voltage_desc: "Seleccione el voltaje estándar de su hogar para cálculos correctos de potencia.",
        costs_currency: "Costos y Moneda",
        tariff_kwh: "Tarifa por kWh",
        display_currency: "Moneda de Visualización",
        monthly_budget_goal: "Meta de Presupuesto Mensual",
        tariff_model: "Modelo Tarifario",

        conventional_desc: "Tarifa única por kWh en cualquier horario.",
        white_tariff: "Tarifa Blanca",
        white_tariff_desc: "Precios varían: Punta (Caro), Intermedio y Fuera de Punta (Barato).",
        peak_start_time: "Hora de Inicio de Punta (Roja)",
        check_bill_desc: "Consulte su factura de luz. Generalmente comienza a las 18h o 19h.",
        peak_time_label: "Horario Punta",
        intermediate_time_label: "Horario Intermedio",
        off_peak_time_label: "Fuera de Punta",
        remaining_hours_weekends: "Resto de horas y fines de semana",
        current_config: "Configuración Actual",

        settings_desc: "Personalice sus preferencias",
        network_voltage: "Voltaje de Red",
        phase_type: "Tipo de Fase",
        informative_only: "Solo informativo",
        zero_to_disable: "0 para desactivar",
        peak_start_hour: "Inicio Hora Punta",
        peak_start_hour_desc: "Hora de inicio de la tarifa más cara.",
        white_tariff_cost_desc: "Costo base (Fuera de Punta)",
        conventional_tariff_cost_desc: "Costo único del kWh",
        conventional: "Convencional",
        base_cost_kwh: "Costo Base kWh",


        appearance_themes: "Apariencia y Temas",
        customize_theme_desc: "Elija el aspecto de su tablero",
        high_priority_alerts_desc: "Alertas críticas de sistema o clima",

        alerts_notifications: "Alertas y Notificaciones",
        high_priority_alerts: "Alertas de Alta Prioridad",
        high_priority_desc: "Notificar sobre consumo excesivo (>6kW) o tormentas.",
        weekly_report: "Reporte Semanal",
        weekly_report_desc: "Reciba un resumen de costos cada lunes.",
        educational_tips: "Consejos Educativos",
        educational_tips_desc: "Mostrar consejos de ahorro en el Tablero.",
        restart_tutorial: "Reiniciar Tutorial",

        single_phase: "Monofásico",
        two_phase: "Bifásico",
        three_phase: "Trifásico",

        // Profile Page
        personal_info: "Información Personal",
        profile_desc: "Administre su información y seguridad.",
        your_name: "Su Nombre",
        display_name_desc: "Cómo se le llamará en el sistema.",
        email: "Correo Electrónico",
        email_change_notice: "Para cambiar su correo, contacte al soporte.",
        display_name: "Nombre de Visualización",
        name_placeholder: "Su nombre",
        name_visibility_desc: "Este nombre será visible en el tablero y reportes.",
        email_managed: "Email (Gestionado por Google)",
        save_changes: "Guardar Cambios",
        profile_updated: "¡Perfil actualizado con éxito!",
        profile_error: "Error al actualizar perfil.",
        secure_account: "Cuenta Segura",
        secure_account_desc: "Usted está autenticado vía Google Secure Login.",

        // Achievements
        tier_bronze: "Bronce",
        tier_silver: "Plata",
        tier_gold: "Oro",
        tier_legendary: "Legendario",
        achievements_desc: "Siga su progreso, eficiencia y dominio del sistema. Desbloquee medallas y equipe su favorita.",
        level: "Nivel",
        equipped: "Equipado",
        progress: "Progreso",

        ach_hello_world_name: "Primer Paso",
        ach_hello_world_desc: "Acceda al Tablero por primera vez.",
        ach_first_spark_name: "Primera Chispa",
        ach_first_spark_desc: "Agregue su primer dispositivo al sistema.",
        ach_observer_name: "Observador",
        ach_observer_desc: "Visite la página del Simulador.",
        ach_theme_park_name: "Estilista",
        ach_theme_park_desc: "Cambie el tema del tablero 3 veces.",
        ach_configurator_name: "Ingeniero",
        ach_configurator_desc: "Ajuste la configuración de tarifa o voltaje.",
        ach_simulation_fan_name: "Científico de Datos",
        ach_simulation_fan_desc: "Ejecute 10 simulaciones de carga.",
        ach_fully_loaded_name: "Casa Inteligente",
        ach_fully_loaded_desc: "Tenga 5 o más dispositivos registrados.",
        ach_night_owl_name: "Búho Nocturno",
        ach_night_owl_desc: "Acceda al sistema entre la 1 AM y las 5 AM.",
        ach_multipower_name: "Multitarea",
        ach_multipower_desc: "Ejecute 3 simulaciones simultáneas.",
        ach_efficiency_expert_name: "Ecológico",
        ach_efficiency_expert_desc: "Registre un dispositivo Solar.",
        ach_solar_titan_name: "Titán Solar",
        ach_solar_titan_desc: "Genere un total de 500 kWh de energía.",
        ach_grid_guardian_name: "Guardián de la Red",
        ach_grid_guardian_desc: "Ejecute 50 Simulaciones.",
        ach_energy_tycoon_name: "Magnate",
        ach_energy_tycoon_desc: "Ahorro virtual acumulado de $ 1,000.00.",
        ach_overload_name: "Sobrecarga",
        ach_overload_desc: "Simule una corriente superior a 50A.",
        ach_collector_name: "Coleccionista",
        ach_collector_desc: "Desbloquee 10 logros.",
        ach_energy_god_name: "Dios de la Energía",
        ach_energy_god_desc: "Genere 1 MegaWatt-hora (1000 kWh).",
        ach_timeless_name: "Atemporal",
        ach_timeless_desc: "Acceda a la aplicación en 7 días diferentes.",
        unlocked_title: "¡Logro Desbloqueado! 🏆",
        unlocked_message: "Desbloqueaste: {name}",

        // Charts
        power: "Potencia",
        realtime_power: "Potencia en Tiempo Real",
        realtime_current: "Corriente en Tiempo Real",

        // Smart Tips
        tip_edu_led: 'Consejo: LED ahorra hasta un 80%.',
        tip_edu_standby: '¿Sabías? Standby cuesta hasta 12%.',
        tip_edu_shower: 'Duchas: -5 min ahorra dinero.',
        tip_edu_fridge: 'Nevera: Evita abrir la puerta.',
        tip_edu_iron: 'Plancha: Plancha todo de una vez.',
        tip_edu_ac_filter: 'Mantenimiento: Limpia filtros AC.',
        tip_edu_natural_light: '¿Día claro? ¡Usa luz natural!',
        tip_edu_peak: 'Evita lavadoras en hora punta.',
        tip_edu_solar_clean: 'Paneles Solares: Revisa limpieza.',
        tip_edu_tv_sleep: '¿TV prendida? Usa Sleep.',
        tip_edu_charger: 'Desenchufa cargadores.',
        tip_edu_seal: 'AC: Cierra puertas y ventanas.',
        tip_peak_active: '¡Hora Punta! Tarifa cara.',
        tip_inter_active: 'Tarifa Intermedia. Precio subiendo.',
        tip_budget_warn: 'Cuidado: 90% presupuesto',
        tip_rain_solar: 'Lluvia reduce generación.',
        tip_storm_alert: '¡Tormenta! Protege equipos.',
        tip_good_solar: '¡Mucho sol! ☀️ Aprovecha.',
        tip_high_temp: 'afuera! AC trabajando duro.',
        tip_low_temp: '¡Noche fría! Calefacción gasta mucho.',
        tip_vampire_power: 'Alto consumo nocturno. ¿Standby?',
        tip_heavy_load: '¡Carga muy alta (>6kW)!',
        tip_weekend_laundry: 'Fin de semana: Tarifa barata.',
        tip_friday_night: '¡Viernes! 🍿 Buen descanso.',
        tip_solar_momentum: '¡Momento Mágico! 🌟 Excedente alto.',
        tip_solar_gold: '¡Beneficio Máximo! 💰 Evitando punta.',
        tip_quiet_night: 'Noche tranquila. Todo bien.',
        tip_ac_efficiency: 'Calor fuera, control dentro. ¡Bien!',
        tip_voltage_instability: 'Voltaje inestable. ¡Riesgo!',
        tip_default_safe: 'Sistema operando normalmente.',

        city_placeholder: "Ciudad...",
        analyzing_system: "Analizando sistema...",
        clear_sky: "Cielo Despejado",
        partly_cloudy: "Parcialmente Nublado",
        rain: "Lluvia",
        storm: "Tormenta",
        normal: "Normal",
        high_priority: "Alta Prioridad",
        warning: "Atención",
        opportunity: "Oportunidad",
        tip: "Consejo",


        off_peak: "Fuera de Punta",
        peak_expensive: "Punta (Caro)",
        intermediate: "Intermedio",
        peak_warning: "¡Tarifa más cara! Evite usar electrodomésticos pesados ahora.",
        intermediate_warning: "Tarifa subiendo. Cuidado con el consumo.",
        off_peak_recommendation: "Mejor momento para usar electrodomésticos pesados.",

        loading: "Cargando...",
        notifications: "Notificaciones",
        new: "nuevas",
        mark_all_read: "Marcar todas como leídas",
        clear_all: "Borrar todo",
        no_notifications: "Nada por aquí...",
        monitoring: "Monitoreando",
        select_device: "Seleccione el Dispositivo",
        select_network_voltage: "Seleccione el Voltaje de Red",
        custom: "Personalizada",
        enter_voltage: "Ingrese el voltaje",
        no_data_export: "Sin datos para exportar.",

        peak_load_title: "Picos de Carga",
        peak_load_desc: "Corriente máxima registrada por día",
        amperes: "Amperios",
        cost_evolution: "Evolución de Costos",
        based_on_tariff: "Basado en la tarifa configurada",
        no_history_data: "Sin datos históricos para este dispositivo.",

        // Notifications
        notif_system_started: "Sistema Iniciado",
        notif_system_started_desc: "Monitoreo en tiempo real activo. Bienvenido a WireSense.",
        notif_peak_load: "Pico de Consumo",
        notif_peak_load_desc: "Detectado pico de 4.2kW en Aire Acondicionado.",
        notif_tariff_update: "Tarifa Actualizada",
        notif_tariff_update_desc: "La tarifa cambió a Intermedia ($ 0.89/kWh).",
        notif_device_connected: "Dispositivo Conectado",
        notif_device_connected_desc: "Nuevo dispositivo 'Smart TV' detectado en la red.",
        notif_goal_reached: "Meta Alcanzada",
        notif_goal_reached_desc: "Usted alcanzó el 80% del presupuesto mensual estipulado.",
        notif_savings_generated: "Ahorro Generado",
        notif_savings_generated_desc: "Sus paneles ahorraron $ 12.50 hoy.",
        notif_voltage_unstable: "Voltaje Inestable",
        notif_voltage_unstable_desc: "Variación de voltaje detectada (118V -> 109V).",
        notif_report_ready: "Reporte Disponible",
        notif_report_ready_desc: "El reporte semanal de eficiencia está listo.",
        error: "Ocurrió un error",
        save: "Guardar",
        cancel: "Cancelar",
        delete: "Eliminar",
        edit: "Editar",
        confirm: "Confirmar",
        configure_system: "Configurar sistema",

        appearance: "Apariencia y Temas",
        language: "Idioma",

        // consumer: "Consumidor", // Moved to Devices Page
        // generator: "Generador" // Moved to Devices Page
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('wiresense_lang') || 'pt';
    });

    const t = (key) => {
        const dict = TRANSLATIONS[language] || TRANSLATIONS.pt;
        return dict[key] || key;
    };

    const changeLanguage = (lang) => {
        if (TRANSLATIONS[lang]) {
            setLanguage(lang);
            localStorage.setItem('wiresense_lang', lang);
        }
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
